// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efbdjwoattqttjkjpwbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmYmRqd29hdHRxdHRqa2pwd2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjU3NjYsImV4cCI6MjA2MDgwMTc2Nn0.VWHi8UeZ2k7Py2lqpoFO3bnBKcjjMrDGB0rbIB-PFJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);